<script setup>
import { ref, computed, onMounted, markRaw, watch } from 'vue'
import { Delete, Upload, Refresh, VideoPlay, VideoPause, Download } from '@element-plus/icons-vue'
import { getModels, getPresets, generateImage, exportImages } from '../api'

const URL = { createObjectURL(value) { return value?.previewUrl || (rawFile(value) ? globalThis.URL.createObjectURL(rawFile(value)) : '') } }
const requestImages = ref(JSON.parse(localStorage.getItem('atelier-request-images') || '[]'))
watch(requestImages, (value) => localStorage.setItem('atelier-request-images', JSON.stringify(value)), { deep: true })

const models = ref([]); const presets = ref([]); const model = ref(''); const presetId = ref(''); const prompt = ref(''); const count = ref(1); const resolution = ref('2K'); const format = ref('png'); const size = ref('2048x2048'); const customWidth = ref(2048); const customHeight = ref(2048); const running = ref(false); const error = ref(''); const controller = ref(null); const preview = ref('')
const materials = ref({ person: [], outfit: [], background: [], pose: [], prop: [], reference: [] })
function fileToDataUrl(file) { return new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(reader.result); reader.onerror = reject; reader.readAsDataURL(file) }) }
const materialLabels = { person: '人物', outfit: '服装', background: '背景', pose: '动作', prop: '道具', reference: '参考图' }
watch(materials, async (value) => { const labeled = []; for (const [key, files] of Object.entries(value)) for (const item of files) { const file = rawFile(item); if (!file) continue; const data = await fileToDataUrl(file); labeled.push({ type: materialLabels[key], data }) } requestImages.value = labeled.map((item) => item.data); localStorage.setItem('atelier-request-materials', JSON.stringify(labeled)) }, { deep: true })
const results = ref([]); const selected = ref(new Set())
const combinationCount = computed(() => Math.max(1, materials.value.person.length) * Math.max(1, materials.value.background.length))
const totalExpected = computed(() => combinationCount.value * Math.max(1, Number(count.value || 1)))
const preset = computed(() => presets.value.find((item) => item.id === presetId.value))
const materialTypes = [{ key: 'person', label: '人物' }, { key: 'outfit', label: '服装' }, { key: 'background', label: '背景' }, { key: 'pose', label: '动作' }, { key: 'prop', label: '道具' }, { key: 'reference', label: '参考图' }]
function rawFile(value) { return value?.raw instanceof File ? value.raw : value instanceof File ? value : value?.file instanceof File ? value.file : null }
function addFiles(key, upload) { const file = rawFile(upload); if (!file || !file.type?.startsWith('image/')) return; if (materials.value[key].some((item) => item.name === file.name && item.size === file.size)) return; materials.value[key].push(markRaw({ file, name: file.name, size: file.size, previewUrl: URL.createObjectURL(file) })) }
function removeFile(key, index) { materials.value[key].splice(index, 1) }
async function refresh() { try { models.value = await getModels(); model.value ||= models.value[0]?.id || ''; presets.value = await getPresets(); presetId.value ||= presets.value[0]?.id || '' } catch (e) { error.value = e.message } }
function clearCurrent() { Object.keys(materials.value).forEach((key) => { materials.value[key] = [] }); results.value = []; selected.value = new Set(); prompt.value = ''; error.value = '' }
async function generate() { if (running.value || !model.value) return; running.value = true; controller.value = new AbortController(); results.value = Array.from({ length: totalExpected.value }, () => ({ loading: true })); try { const people = materials.value.person.length ? materials.value.person : [null]; const backgrounds = materials.value.background.length ? materials.value.background : [null]; const outputs = []; for (const person of people) for (const background of backgrounds) { const labeled = []; for (const [key, item] of [['person', person], ['background', background], ...['outfit', 'pose', 'prop', 'reference'].flatMap((key) => materials.value[key].map((value) => [key, value]))]) { const file = rawFile(item); if (file) labeled.push({ type: materialLabels[key], data: await fileToDataUrl(file) }) } const rolePrompt = '程序素材角色：第一类为人物素材，只决定最终人物身份、脸部、发型、服装和体态；第二类为背景素材，只决定最终场景和环境；后续素材为服装、动作、道具和参考图，仅作为对应属性参考。严格使用人物素材中的人物，使用背景素材作为场景；参考图只参考构图、人物位置、景别、透视和光线，不得使用参考图中的人物或背景替换指定素材。保持人物与背景的空间比例一致，不得放大人物或改变景别。'; const finalPrompt = `${rolePrompt}\n${preset.value?.prompt || ''}\n${prompt.value}`; for (let index = 0; index < count.value; index += 1) { if (controller.value.signal.aborted) throw new DOMException('Aborted', 'AbortError'); const response = await generateImage({ model: model.value, prompt: finalPrompt, images: labeled.map((item) => item.data), materials: labeled, n: 1, size: size.value === 'custom' ? `${customWidth.value}x${customHeight.value}` : size.value, quality: resolution.value === '4K' ? 'high' : 'medium', format: format.value }, { signal: controller.value.signal }); outputs.push(...(response.data || []).map((item) => ({ url: item.url || (item.b64_json ? `data:image/png;base64,${item.b64_json}` : '') }))) } } results.value = outputs } catch (e) { if (e.name !== 'AbortError') error.value = e.message; results.value = [] } finally { running.value = false; controller.value = null } }
function stop() { controller.value?.abort(); running.value = false; results.value = []; error.value = '已停止生成' }
function toggle(index) { selected.value.has(index) ? selected.value.delete(index) : selected.value.add(index) }
async function exportSelected() { await exportImages([...selected.value].map((index) => results.value[index]?.url).filter(Boolean)) }
onMounted(() => { refresh(); requestAnimationFrame(() => { const keys = materialTypes.map((item) => item.key); document.querySelectorAll('.material-box input[type="file"]').forEach((input, index) => { input.addEventListener('change', (event) => Array.from(event.target.files || []).forEach((file) => addFiles(keys[index], file))) }) }) })
</script>

<template>
  <section class="intro"><div><h2>创作工作台</h2><p>生成过程中配置会锁定，停止后才能修改。</p></div><el-button :icon="Refresh" @click="refresh" :disabled="running">刷新模型与预设</el-button></section>
  <el-form :disabled="running" label-position="top" class="workspace-form">
    <div class="grid">
      <section class="panel"><span class="eyebrow">01 / 输入素材</span><h3>素材组合</h3><p class="muted">每类素材支持多张，点击缩略图右上角删除。</p><div class="assets"><div v-for="item in materialTypes" :key="item.key" class="material-box"><b>{{ item.label }}</b><el-upload action="#" :auto-upload="false" :show-file-list="false" multiple accept="image/*" @change="addFiles(item.key, $event)"><el-button :icon="Upload" plain>添加{{ item.label }}</el-button></el-upload><div class="thumbs"><div v-for="(file,index) in materials[item.key]" :key="file.uid || file.name + index" class="thumb"><el-image :src="URL.createObjectURL(file)" fit="cover" :preview-src-list="materials[item.key].map((item) => URL.createObjectURL(item))" /><el-button class="thumb-delete" :icon="Delete" circle size="small" @click="removeFile(item.key,index)" /></div></div><small>已添加 {{ materials[item.key].length }} 张</small></div></div></section>
      <section class="panel config-panel"><span class="eyebrow">02 / 生成配置</span><h3>生成配置</h3><el-form-item label="模型"><el-select v-model="model" placeholder="选择模型" filterable><el-option v-for="item in models" :key="item.id" :label="item.id" :value="item.id" /></el-select></el-form-item><el-form-item label="提示词预设"><el-select v-model="presetId" placeholder="未选择预设"><el-option v-for="item in presets" :key="item.id" :label="item.name" :value="item.id" /></el-select></el-form-item><p v-if="preset" class="preset-preview">{{ preset.prompt }}</p><el-form-item label="补充提示词"><el-input v-model="prompt" type="textarea" :rows="4" placeholder="仅填写本次额外要求" /></el-form-item><el-form-item label="尺寸"><el-radio-group v-model="size"><el-radio-button label="2048x2048">2048×2048</el-radio-button><el-radio-button label="2560x1440">2560×1440</el-radio-button><el-radio-button label="1440x2560">1440×2560</el-radio-button><el-radio-button label="3024x1296">3024×1296</el-radio-button><el-radio-button label="custom">自定义</el-radio-button></el-radio-group></el-form-item><div v-if="size === 'custom'" class="custom-size"><el-input-number v-model="customWidth" :min="256" :step="8" /><span>×</span><el-input-number v-model="customHeight" :min="256" :step="8" /></div><div class="settings-grid"><el-form-item label="分辨率"><el-select v-model="resolution"><el-option label="2K" value="2K" /><el-option label="4K" value="4K" /></el-select></el-form-item><el-form-item label="格式"><el-select v-model="format"><el-option label="PNG" value="png" /><el-option label="JPG" value="jpg" /><el-option label="WebP" value="webp" /></el-select></el-form-item><el-form-item label="数量"><el-input-number v-model="count" :min="1" :max="100" /></el-form-item></div><el-button type="primary" class="clear-button" @click="clearCurrent">清空当前</el-button></section>
    </div>
  </el-form>
  <div class="generation-actions"><el-button v-if="!running" type="primary" :icon="VideoPlay" @click="generate">开始生成</el-button><el-button v-else type="danger" :icon="VideoPause" @click="stop">停止生成</el-button></div>
  <section class="panel queue"><div class="queue-head"><div><span class="eyebrow">03 / 结果画廊</span><h3>样片预览</h3></div><el-button :icon="Download" :disabled="!selected.size" @click="exportSelected">导出已选 ({{ selected.size }})</el-button></div><el-alert v-if="error" :title="error" type="error" show-icon /><div v-if="!results.length" class="empty">暂无生成结果</div><div v-else class="gallery"><div v-for="(item,index) in results" :key="index" class="result-card"><div v-if="item.loading" class="loading-placeholder">正在生成样片 {{ index + 1 }}<i /></div><template v-else><el-image :src="item.url" fit="cover" :preview-src-list="results.filter((item) => item.url).map((item) => item.url)" /><el-checkbox :model-value="selected.has(index)" class="result-check" @change="toggle(index)" /></template></div></div></section>
</template>
