const BASE = 'http://127.0.0.1:4317'
export async function getSettings() { const response = await fetch(`${BASE}/api/settings`); if (!response.ok) throw new Error('本地 Node 服务未启动'); return response.json() }
export async function saveSettings(settings) { const response = await fetch(`${BASE}/api/settings`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(settings) }); if (!response.ok) throw new Error('配置保存失败') }
export async function getModels() { const response = await fetch(`${BASE}/api/models`); const data = await response.json(); if (!response.ok) throw new Error(data.error || '模型读取失败'); return data.data || data.models || [] }
export async function generateImage(input, options = {}) { const cachedImages = JSON.parse(localStorage.getItem('atelier-request-images') || '[]'); const cachedMaterials = JSON.parse(localStorage.getItem('atelier-request-materials') || '[]'); const body = { ...input, images: input.images?.length ? input.images : cachedImages, materials: input.materials?.length ? input.materials : cachedMaterials }; const response = await fetch(`${BASE}/api/generate`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body), signal: options.signal }); const data = await response.json(); if (!response.ok) throw new Error(data.error?.message || data.error || `HTTP ${response.status}`); return data }
export async function getPresets() { const response = await fetch(`${BASE}/api/presets`); if (!response.ok) throw new Error('预设读取失败'); return response.json() }
export async function savePresets(value) { const response = await fetch(`${BASE}/api/presets`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(value) }); if (!response.ok) throw new Error('预设保存失败') }
export async function getRecords() { const response = await fetch(`${BASE}/api/records`); if (!response.ok) throw new Error('生成记录读取失败'); return response.json() }
export async function exportImages(urls) { const response = await fetch(`${BASE}/api/export`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ urls }) }); if (!response.ok) throw new Error('批量导出失败'); const blob = await response.blob(); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = 'atelier-images.zip'; link.click(); URL.revokeObjectURL(link.href) }
export function downloadUrl(url) { return `${BASE}/api/download?url=${encodeURIComponent(url)}` }
