import { createApp } from 'vue';
import ElementPlus from 'element-plus'
import 'element-plus/dist/index.css'
import { createPinia } from 'pinia';
import { createRouter, createWebHashHistory } from 'vue-router';
import App from './App.vue';
import './styles.css';
import './fixes.css';
import './workspace-fixes.css';
import './workspace-interactions.css';
import './history.css';
import './generation-lock.css';
import './custom-size.css';
import './interaction-polish.css';
import './element-workspace.css';
import './compact-workspace.css';
import './prototype-layout.css';
import './prototype-refine.css';
import './prototype-studio.css';
import './v5-theme.css';
import './v5-global-fix.css';
import './v5-structure.css';
import './v5-interaction-fix.css';
import './v5-viewport-fix.css';
import './v5-config-column.css';
import './v5-generation-bar.css';
import './v5-status-height-fix.css';
import './v5-result-focus.css';
import './upload-progress.css';
import './v5-material-width.css';
import './preview-progress-fix.css';
import './upload-workbench.css';
import './edit-region.css';
import './generation-panel-layout.css';
import './top-workspace-layout.css';
import './composer-layout.css';
const router=createRouter({history:createWebHashHistory(),routes:[{path:'/',component:()=>import('./views/Workspace.vue')},{path:'/library',component:()=>import('./views/Library.vue')},{path:'/presets',component:()=>import('./views/Presets.vue')},{path:'/history',component:()=>import('./views/History.vue')},{path:'/apis',component:()=>import('./views/ApiManagement.vue')} ]});
createApp(App).use(createPinia()).use(router).use(ElementPlus).mount('#app');
